name              'proj-inkscape'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Installs/Configures proj-inkscape'
issues_url        'https://github.com/osuosl-cookbooks/proj-inkscape/issues'
source_url        'https://github.com/osuosl-cookbooks/proj-inkscape'
chef_version      '>= 18.0'
version           '0.1.0'

supports          'almalinux', '~> 9.0'
